# Generated by Django 4.0.5 on 2022-06-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('cpfs', models.TextField(blank=True, default='')),
                ('cnpjs', models.TextField(blank=True, default='')),
                ('ceps', models.TextField(blank=True, default='')),
            ],
        ),
    ]
