# Generated by Django 4.0.5 on 2022-06-27 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_docs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='ceps',
        ),
        migrations.RemoveField(
            model_name='text',
            name='cnpjs',
        ),
        migrations.RemoveField(
            model_name='text',
            name='cpfs',
        ),
    ]
