# Generated by Django 4.0.5 on 2022-06-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='cpfs',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
