# Generated by Django 4.0.5 on 2022-06-30 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_docs', '0002_remove_text_ceps_remove_text_cnpjs_remove_text_cpfs'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='cpfs',
            field=models.TextField(blank=True),
        ),
    ]
