# Generated by Django 4.0.5 on 2022-06-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_docs', '0002_text_cpfs_alter_text_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cpf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=11)),
            ],
        ),
        migrations.RemoveField(
            model_name='text',
            name='cpfs',
        ),
        migrations.AddField(
            model_name='text',
            name='cpfs',
            field=models.ManyToManyField(related_name='texts', to='get_docs.cpf'),
        ),
    ]
