# Generated by Django 4.0.5 on 2022-07-03 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_docs', '0003_text_cpfs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='cpfs',
        ),
    ]
