# Generated by Django 4.0.5 on 2022-06-24 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_docs', '0003_cpf_remove_text_cpfs_text_cpfs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='cpfs',
        ),
        migrations.AddField(
            model_name='text',
            name='cpfs',
            field=models.TextField(blank=True),
        ),
    ]
