# Generated by Django 4.0.5 on 2022-06-24 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_docs', '0004_remove_text_cpfs_text_cpfs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='cpfs',
        ),
        migrations.AddField(
            model_name='text',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
