# Generated by Django 4.0.5 on 2022-06-24 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_docs', '0005_remove_text_cpfs_text_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
