# Generated by Django 4.0.5 on 2022-06-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_docs', '0006_alter_text_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='cpfs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
