# Generated by Django 4.0.5 on 2022-06-25 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('get_docs', '0007_text_cpfs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cpf',
        ),
        migrations.RemoveField(
            model_name='text',
            name='cpfs',
        ),
        migrations.RemoveField(
            model_name='text',
            name='file',
        ),
    ]
