# Generated by Django 4.0.5 on 2022-06-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_docs', '0008_delete_cpf_remove_text_cpfs_remove_text_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='cpfs',
            field=models.TextField(blank=True, default=''),
        ),
    ]
