# Generated by Django 4.0.5 on 2022-06-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_docs', '0009_text_cpfs'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='ceps',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='text',
            name='cnpjs',
            field=models.TextField(blank=True, default=''),
        ),
    ]
