# Generated by Django 4.0.5 on 2022-07-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('cpfs_found', models.TextField(blank=True)),
                ('cnpjs_found', models.TextField(blank=True)),
                ('ceps_found', models.TextField(blank=True)),
            ],
        ),
    ]
